Repository public-transport/transitous, pull requests merged in 2025-05, with the labels that each got.

#1101 Update sources
  feeds/it.json
Labels: data sources

#1122 Add Adelaide Metro (AU)
  feeds/au.json
Labels: data sources

#1111 Yet another pl.json update
  feeds/pl.json
Labels: data sources

#1127 Add Nextbike GBFS for Dresden, Leipzig and Halle
  feeds/de.json
Labels: data sources

#1144 Add python client to libraries
  website/content/api.html
Labels: documentation

#1129 Rename IN-TG to IN-TS
  feeds/in-ts.json
Labels: bug, data sources
